version: 2.1

orbs:
  nx: nrwl/nx@1.1.2

jobs:
  fe-flow:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - restore_cache:
          keys: 
            - npm-deps-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          # Check if node_modules exist from cache, otherwise run npm ci again
          name: Install node dependencies
          command: "[ ! -d node_modules ] && yarn install || echo package.json and package-lock.json unchanged. Using cached dependencies."
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: yarn nx test monofe
          name: Run angular tests
      - run:
          command: yarn nx build monofe --prod
          name: Build production
      - run:
          command: |
            scp -o StrictHostKeyChecking=no -r dist/apps/monofe/* $USER@188.166.104.56:/home/$USER/deploy
            ssh -o StrictHostKeyChecking=no $USER@$DEMO_SERVER_ADRESS 'nohup /home/$USER/deploy.sh'
          name: Copy files to server

workflows:
  version: 2
  test-build-fe:
    jobs:
      - fe-flow: 
          filters:
            tags:
              only: 
                - main