version: 2.1

orbs:
  nx: nrwl/nx@1.1.2

jobs:
  fe-flow:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run:
          command: npm ci
          name: Install dependencies
      - run:
          command: yarn nx test monofe
          name: Run angular tests
      - run:
          command: yarn nx build monofe --prod
          name: Build production
      - run:
          command: scp -o StrictHostKeyChecking=no -r dist/* $USER@188.166.104.56:/var/www/html
          name: Copy files to server

workflows:
  test-build-fe:
    jobs:
      - fe-flow